### ISSUE TITLE
Issue with floatrange intersection

### ISSUE THREAD

**Issue by lgharibashvili** [runfalk/spans#18]
Hello,

There seems to be a bug with floatrange intersection (or maybe I do not understand it correctly).
It can be observed when first range has same upper value as the lower value of the second range, but lower value of the second range is not included.

Here is an example:
`floatrange(0.0, 5.0, upper_inc=True).intersection(floatrange(5.0, lower_inc=False))`

Which results in:
`floatrange(5.0, 5.0, lower_inc=False, upper_inc=True)`

As I understand, expected result should be an empty set, because 5.0 is not included in the first range, so it can also not be an intersection.
The result is also misleading, because same number is both included and not included (a Schrödinger range?).

**Comment by lgharibashvili** [comment]
The problem seems to be in __lt__ method of _Bound class (line 65). 
```
elif self.value == other.value:
    if self.is_lower:
        if self.inc:
            return other.is_lower ^ other.inc
        else:
            return not other.is_lower and other.inc # <--
```

In case when both values are same and **self** is lower and not included, then we have four cases:
1. **other** is lower and not included - the bounds are equal, so result should be False.
2. **other** is lower and included - in this case **self** is greater than the **other**. **other** equals its value, but **self** is a little greater than its value.
3. **other** is upper and is not included - **self** is still greater. **other** is a little smaller than its value and **self** is a little greater than its value.
4. **other** is upper and is included (this is the case of the bug) - **self** is greater again. **other** equals its value, but **self** is a little greater than its value.

From these, it seems that we get False in all cases. Please correct me if I'm missing anything.

**Comment by runfalk** [comment]
You're right that this is wrong. The same problem should apply to all non-discrete range types. The problem is that we only check that `upper >= lower`.

https://github.com/runfalk/spans/blob/master/spans/types.py#L139

Like you say it makes sense to normalize this into an empty set. Discrete ranges are normalized but I didn't see a scenario where we needed to do that for normal ranges. Since this library is intended to be used with Postgres I usually consult that as the source of truth:

```
# SELECT numrange(5.0, 5.0, '(]');
 numrange 
----------
 empty
(1 row)

# SELECT lower(numrange(5.0, 5.0, '(]'));
 lower 
-------
      
(1 row)
```

So it does indeed normalize it. I'm happy to merge a PR that addresses this. If you make a PR please also make sure to add a regression test to the suite. There should already be a few ones you can use as a template.

**Comment by lgharibashvili** [comment]
Sorry for the delay. I'll make a PR.

Regarding normalization, I can add additional check in the constructor for case when upper == lower and at least one of the boundaries is not included. In such case the range will be empty.

I also checked it in Postgres:
```
SELECT numrange(5.0, 5.0, '[]');
numrange([5.0, 5.0])

SELECT numrange(5.0, 5.0, '()');
numrange(empty)

SELECT numrange(5.0, 5.0, '(]');
numrange(empty)

SELECT numrange(5.0, 5.0, '[)');
numrange(empty)
```

**Comment by runfalk** [comment]
Perfect, that sounds like a good fix. Thank you for reporting back!
