### ISSUE TITLE
Empty sets are not really empty, leading to issues when iterating over them

### ISSUE THREAD

**Issue by der-michik** [runfalk/spans#4]
If have a program where I loop over a set and do things with every range in that set. That just works as intended for non-empty sets of non-empty ranges. However, if a rangeset is empty, strange things happen. First, create an empty rangeset:

    In [1]: from spans import intrangeset
    In [2]: s = intrangeset([])
    In [3]: len(s)
    Out[3]: 0

As expected, the size of an empty set is 0 as it contains no elements. However, it in fact contains one element, which is an empty range:

    In [4]: s._list[0]
    Out[4]: intrange(empty)

This leads to funny behaviour, since iterating over the set simply seems to iterate over the internal list:

    In [5]: for r in s:
       ...:     print(r)
       ...:     
    intrange(empty)

The real issue occurs when trying to do anything with all the ranges in that set, e.g. like this:

    In [6]: for r in s:
       ...:     for i in r:
       ...:         print(i)
       ...:         
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-5-beda3179b2cf> in <module>()
          1 for r in s:
    ----> 2     for i in r:
          3         print(i)
          4 
    
    /usr/local/lib/python3.4/dist-packages/spans/types.py in __iter__(self)
        791     def __iter__(self):
        792         next = self.lower
    --> 793         while next < self.upper:
        794             yield next
        795             next = self.next(next)
    
    TypeError: unorderable types: NoneType() < NoneType()

Note that the Traceback is misleading: It fails when trying to iterate over an emptry range which has no lower and upper limit (Maybe that's a different bug for ranges without a lower bound?). However, that should not have happened in the first place as the outer loop already should have done nothing at all.

The problem seems to be that `__iter__` of a set always returns the iterator of its `_list` (l. 158 in settypes.py). At the moment I don't have the time to deeper look into the code to see if it is useful that the `_list` of sets contains an element for empty sets. In any case, something similar like in `__len__` should fix this, e.g. like that:

    return iter(self._list) if self else iter([])

**Comment by runfalk** [comment]
This is indeed erroneous behavior. Your suggested fix is the simple way, and do pass all tests. I skimmed through the code to see why I chose the empty set route. Some methods expect that there is always a set available:

- `contains()`/`__contains__()` would always return False when tested with an empty set. This could be handled using a special case to return `True` when given an empty set.
- `span()` expect at least one element and will crash otherwise. This can be solved by a special case returning `self.type.empty()`, since it already has a special case for the empty set.

However, some methods have special cases because of the empty set possibility:

- `__repr__()` could be shortened without the mandatory empty set.
- `__nonzero__()`/`__bool__()` could be simplified to a simple `bool(self._list)`.
- `__iter__()` could remain the same as now.
- `__len__()` wouldn't need a special case.
- `remove()` has a special case to make sure there is always an empty set in `self._list`.

I can't remember exactly why I chose the current solution, but these to lists does make it seem like it would be more natural to make `self._list = []` when the set is empty. I will try to implement that and see if it breaks anything.

**Comment by runfalk** [comment]
I think I have fixed your problem now. I opted for the fix where `self._list = []` for empty range sets. I think my original reasoning was that the empty set is part of all range sets, which is why it makes sense to return it. However, your use case proves it may just complicate things with no obvious benefit.

Let me know if the fix works for you.

**Comment by der-michik** [comment]
Seems to work just fine, thank you!
